global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lims-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lims-app:8080']
        labels:
          application: 'lims-prod'
          instance: 'lims-app-01'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
